services:
  # Banco de Dados (Postgres)
  db:
    image: postgres:18-alpine
    container_name: nestjs_bid_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5str0ngP@ssw0rd
      POSTGRES_DB: bid_database
    ports:
      - "5432:5432"
    healthcheck: # Pleno/Senior move: garante que o banco está saudável
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache e Filas (Redis)
  redis:
    image: redis:alpine
    container_name: nestjs_bid_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: